version: '3.8'

services:

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./culinaryguide.client/Dockerfile
    volumes:
      - './culinaryguide.client:/app'
      - '/app/node_modules'
    ports:
      - 5173:5173
    networks:
      - culinaryguide-network

networks:
  culinaryguide-network:
    driver: bridge
